# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: A Unity Game Developer Journey
email: meozdemir90@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my journey of learning and sharing about mostly Unity Game Development. I will try to launch a indie game on steam platform.
  Meanwhile I will learn and share about Web Development with current technologies. Hope to get a job as a Web Developer or Unity Game Developer.
twitter_username: enesozdemir90
github_username: enesozdemir
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Enes Ozdemir"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "My frustrating journey to Unity Game Development"
  links:
    - label: "Demos & Free Games"
      icon: "fab fa-itch-io"
      url: "https://enesozdemir.itch.io/"
    - label: "Mobile Games"
      icon: "fab fa-google-play"
      url: "https://play.google.com/store/apps/dev?id=5556705161399632719"  
    - label: "Follow me here!"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/enesozdemir90"
    - label: "Some of my codes"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/enesozdemir"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/kenz_games_"
    - label: "Vlogs & Tutorials"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@meozdemir90"
    - label: "Mr. Business"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/meozdemir90/"  

footer:
  links:
    - label: "Demos & Free Games"
      icon: "fab fa-itch-io"
      url: "https://enesozdemir.itch.io/"
    - label: "Mobile Games"
      icon: "fab fa-google-play"
      url: "https://play.google.com/store/apps/dev?id=5556705161399632719"  
    - label: "Follow me here!"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/enesozdemir90"
    - label: "Some of my codes"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/enesozdemir"
    - label: "Vlogs & Tutorials"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@meozdemir90"
    - label: "Mr. Business"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/meozdemir90/"
      
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  -scope:
      path: "_portfolio"
      type: pages
    values:
      layout: collection

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
portfolio-archive:
  tyoe: grid
  path: /portfolio/
